services:
  main:
    build:
      context: ..
      dockerfile: image/Dockerfile
      args:
        - DOT_LOCALHOST=1
    environment:
      - DOMAIN_PREFIX=http://
      - DOMAIN_SUFFIX=.localhost:2015
    ports:
      - 2015:2015
