name: dnscontrol push

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  dnscontrol:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: ./.devcontainer/setup.sh
      # - run: ./dns/bin/push
      - run: ./bin/preview --expect-no-changes
        working-directory: dns/
        env: 
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          SWARMSIM_COM_SECRET1: ${{ secrets.SWARMSIM_COM_SECRET1 }}
          SWARMSIM_COM_SECRET2: ${{ secrets.SWARMSIM_COM_SECRET2 }}

      # TODO: CI needs tf state storage backend
      #- run: |
      #    tofu init
      #    tofu plan --detailed-exitcode
      #  working-directory: tf/
      #  env: 
      #    CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      #    CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}