name: dnscontrol push

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  dnscontrol:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: ./.devcontainer/setup.sh
      - run: ./bin/preview
      # - run: ./bin/push
