# If this fails, dnscontrol or opentofu have diffs. Real state has diverged from the infrastructure code; drift.
# CI doesn't apply changes; you're expected to apply changes manually!
name: drift-check

on:
  push:
    branches: ["main"]
  schedule:
    # "At 07:52 on Sunday."
    # https://crontab.guru/#52_7_*_*_0
    # https://time.is/0752AM_in_UTC
    # run on a schedule because config can drift without code changes.
    # in fact, it usually drifts because I forgot there was code to change
    - cron: '52 7 * * 0'
  workflow_dispatch:

jobs:
  dnscontrol:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: ./.devcontainer/setup.sh

      - run: ./bin/preview --expect-no-changes
        working-directory: dns/
        env: 
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          SWARMSIM_COM_SECRET1: ${{ secrets.SWARMSIM_COM_SECRET1 }}
          SWARMSIM_COM_SECRET2: ${{ secrets.SWARMSIM_COM_SECRET2 }}

  opentofu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: ./.devcontainer/setup.sh
      - run: ./tf/bin/ci
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_R2_BACKEND_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_BACKEND_SECRET_KEY }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}